### PR TITLE
Use grumphp at least v0.18 and captainhook at least v5

### PR DESCRIPTION
**Pull request by Ig0r-M-magic42**

### CODE REVIEW

**Review by sebastianfeldmann — APPROVED** [review]
Looks great! Thanks!

**Comment by Ig0r-M-magic42** [comment]
Waaait, but, testing :(.

P.S. thanks for the release

**Comment by sebastianfeldmann** [comment]
Sorry... trigger fingers ;)
Let me know if you find any issues so we can do a patch release  :)

**Comment by Ig0r-M-magic42** [comment]
Will do :)

**Pull request merged**
